# Generated by Django 6.0.3 on 2026-04-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_clinic_payment_clinic_and_more'),
        ('treatments', '0003_dentalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='treatments.treatment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('zaad', 'Zaad (Somali Mobile Money)'), ('edahab', 'E-Dahab (Somali Mobile Money)'), ('sahal', 'Sahal (Somali Mobile Money)'), ('insurance', 'Insurance'), ('company', 'Company/Employer'), ('installment', 'Payment Plan/Installment'), ('other', 'Other')], max_length=20),
        ),
    ]
