# Generated by Django 6.0.3 on 2026-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
