# Generated by Django 6.0.3 on 2026-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_subscription_is_on_trial_subscription_trial_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial_expired',
            field=models.BooleanField(default=False),
        ),
    ]
