# Generated by Django 6.0.3 on 2026-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_treatment_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('preventive', 'Preventive'), ('restorative', 'Restorative'), ('endodontics', 'Endodontics (RCT)'), ('periodontics', 'Periodontics'), ('prosthodontics', 'Prosthodontics'), ('oral_surgery', 'Oral Surgery'), ('orthodontics', 'Orthodontics'), ('cosmetic', 'Cosmetic'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=30)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_appointment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dental Service',
                'verbose_name_plural': 'Dental Services',
                'ordering': ['category', 'name'],
            },
        ),
    ]
