# Generated by Django 6.0.3 on 2026-04-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_dentalservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentTemplate',
        ),
        migrations.AddField(
            model_name='treatment',
            name='dental_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='treatments.dentalservice'),
        ),
    ]
