# Generated by Django 6.0.3 on 2026-04-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_invoice_treatment_invoiceitem_treatment_and_more'),
        ('treatments', '0004_delete_treatmenttemplate_treatment_dental_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='billing.invoice'),
        ),
    ]
